package com.example.springproject.security;

public interface SecurityRoles {
    String ROLES_PREFIX = "ROLE_";
    String ROLE_ADMIN = "SUPER_ADMIN";
    String CUSTOMER_ADMIN = "CUSTOMER_ADMIN";
    String CUSTOMER_READ = "CUSTOMER_READ";
    String CUSTOMER_CREATE = "CUSTOMER_CREATE";
    String CUSTOMER_DELETE = "CUSTOMER_DELETE";
    String CUSTOMER_PAGE_VIEW = "CUSTOMER_PAGE_VIEW";

    String DEPARTMENT_ADMIN = "DEPARTMENT_ADMIN";
    String DEPARTMENT_READ = "DEPARTMENT_READ";
    String DEPARTMENT_CREATE = "DEPARTMENT_CRATE";
    String DEPARTMENT_DELETE = "DEPARTMENT_DELETE";
    String DEPARTMENT_PAGE_VIEW = "DEPARTMENT_PAGE_VIEW";

    String EMPLOYEE_ADMIN = "EMPLOYEE_ADMIN";
    String EMPLOYEE_READ = "EMPLOYEE_CREATE";
    String EMPLOYEE_CREATE = "EMPLOYEE_CREATE";
    String EMPLOYEE_DELETE = "EMPLOYEE_DELETE";
    String EMPLOYEE_PAGE_VIEW = "EMPLOYEE_PAGE_VIEW";

}
